# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10.18

jobs:
  build:
    <<: *defaults 
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: 
          name: Install javascript dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Compile Solidity
          command: npm run compile-solidity

      - run:
          name: Run TypeScript linter
          command: npm run lint-typescript

      - run:
          name: Compile TypeScript
          command: npm run compile-typescript

      - persist_to_workspace:
          root: ~/repo
          paths: [ "." ]
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - run:
          name: Install IPFS node
          command: |
            wget https://dist.ipfs.io/go-ipfs/v0.4.22/go-ipfs_v0.4.22_linux-amd64.tar.gz
            tar xvfz go-ipfs_v0.4.22_linux-amd64.tar.gz 
            ./go-ipfs/ipfs init

      - run:
          name: Start IPFS node
          command: ./go-ipfs/ipfs daemon
          background: true

      - run: 
          name: Install Ethereum node
          command: |
            npm i -g ganache-cli@latest

      - run:
          name: Start Ethereum node
          command: nohup bash -c "ganache-cli 2>&1 &"

      - run: 
          name: Wait for services to start
          command: sleep 5

      - run:
          name: Run tests
          command: npm test
  publish:
    <<: *defaults 
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with Javascript package registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish Javascript package
          command: npm publish
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/      
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
                ignore: /.*/
